import pyautogui
import time
pyautogui.PAUSE = 0.3

pyautogui.FAILSAFE = True

time.sleep(5)

#pyautogui.click(x=263, y=536)
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("u")
time.sleep(0.5)
pyautogui.press("i")
pyautogui.press("i")
pyautogui.press("i")
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("y")
pyautogui.press("y")
pyautogui.press("t")
pyautogui.press("o")
pyautogui.press("i")
pyautogui.press("u")
pyautogui.press("u")
pyautogui.press("u")
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("u")
pyautogui.press("i")
pyautogui.press("i")
pyautogui.press("i")
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("u")
pyautogui.press("i")
pyautogui.press("i")
pyautogui.press("i")
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("y")
pyautogui.press("y")
pyautogui.press("t")
pyautogui.press("o")
pyautogui.press("i")
pyautogui.press("u")
pyautogui.press("u")
pyautogui.press("u")
pyautogui.press("t")
pyautogui.press("y")
pyautogui.press("u")
pyautogui.press("i")
pyautogui.press("i")
pyautogui.press("i")
